# Load Raw Data and Packages

In [1]:
import pandas as pd
import numpy as np

In [2]:
H21RawData=pd.read_csv("../../data/raw/world-happiness-report-2021.csv")
H19RawData=pd.read_csv('../../data/raw/2019.csv')
H18RawData=pd.read_csv('../../data/raw/2018.csv')
H17RawData=pd.read_csv('../../data/raw/2017.csv')
H16RawData=pd.read_csv('../../data/raw/2016.csv')
H15RawData=pd.read_csv('../../data/raw/2015.csv')
LivCostRawData=pd.read_csv('../../data/raw/cost_of_living 2020.csv')
GDPRawData=pd.read_csv('../../data/raw/gdp.csv')
H20RawData=pd.read_csv('../../data/raw/world-happiness-report.csv')

# Method Chain

In [3]:
H16RawData

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [4]:
def load_process(path_to_csv):
# Method Chain 1
    df1=(
       pd.read_csv(path_to_csv)
       .drop(['Family','Freedom'],axis=1)
       .dropna(subset=['Happiness Score'])
    )
# Method Chain 2  
    df2=(
         df1
        .sort_values('Country')
        .rename(columns={'Country':'Country_Sorted'})
        .reset_index
      
    )
    
    return df2

In [5]:
load_process('../../data/raw/2016.csv')

<bound method DataFrame.reset_index of     Country_Sorted                           Region  Happiness Rank  \
153    Afghanistan                    Southern Asia             154
108        Albania       Central and Eastern Europe             109
37         Algeria  Middle East and Northern Africa              38
140         Angola               Sub-Saharan Africa             141
25       Argentina      Latin America and Caribbean              26
..             ...                              ...             ...
43       Venezuela      Latin America and Caribbean              44
95         Vietnam                Southeastern Asia              96
146          Yemen  Middle East and Northern Africa             147
105         Zambia               Sub-Saharan Africa             106
130       Zimbabwe               Sub-Saharan Africa             131

     Happiness Score  Lower Confidence Interval  Upper Confidence Interval  \
153            3.360                      3.288                      3.432
108            4.655                      4.546                      4.764
37             6.355                      6.227                      6.483
140            3.866                      3.753                      3.979
25             6.650                      6.560                      6.740
..               ...                        ...                        ...
43             6.084                      5.973                      6.195
95             5.061                      4.991                      5.131
146            3.724                      3.621                      3.827
105            4.795                      4.645                      4.945
130            4.193                      4.101                      4.285

     Economy (GDP per Capita)  Health (Life Expectancy)  \
153                   0.38227                   0.17344
108                   0.95530                   0.73007
37                    1.05266                   0.61804
140                   0.84731                   0.04991
25                    1.15137                   0.69711
..                        ...                       ...
43                    1.13367                   0.61904
95                    0.74037                   0.66157
146                   0.57939                   0.31048
105                   0.61202                   0.23573
130                   0.35041                   0.15950

     Trust (Government Corruption)  Generosity  Dystopia Residual
153                        0.07112     0.31268            2.14558
108                        0.05301     0.16840            1.92816
37                         0.16157     0.07044            3.40904
140                        0.08434     0.12071            2.09459
25                         0.07296     0.10989            3.12985
..                             ...         ...                ...
43                         0.08304     0.04250            2.97468
95                         0.11556     0.25075            1.94180
146                        0.05892     0.09821            1.97295
105                        0.11479     0.17866            2.58991
130                        0.08582     0.18503            2.44270

[157 rows x 11 columns]>

In [6]:
def process_df(DataFrame):
    df=(DataFrame
          .drop(['Family','Freedom'],axis=1)
          .dropna(subset=['Happiness Score'])
          .reset_index(drop=True)
          .groupby('Region')['Happiness Rank']
          .max()
          .sort_values()
          .to_frame()
       )
    return df

In [7]:
process_df(H16RawData)

                                 Happiness Rank
Region
Australia and New Zealand                     9
North America                                13
Western Europe                               99
Eastern Asia                                101
Central and Eastern Europe                  129
Latin America and Caribbean                 136
Southeastern Asia                           140
Southern Asia                               154
Middle East and Northern Africa             156
Sub-Saharan Africa                          157